FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /home/app

COPY ./requirements.txt .

RUN pip3 install --upgrade pip && pip3 install --no-cache-dir -r requirements.txt

CMD [ "python", "server.py" ]