version: '3.9'

services:
  grpc_client:
    build:
      context: ./client
      dockerfile: dockerfile
    image: grpc_client:hello_world
    volumes:
      - ./client:/home/app
    ports:
      - "8000:8000"
    command: uvicorn app:app --reload --port 8000 --host 0.0.0.0
  
  grpc_server:
    build:
      context: ./server
      dockerfile: dockerfile
    image: grpc_server:hello_world
    volumes:
      - ./server:/home/app
    ports:
      - "50051:50051"
    command: python server.py

    